app = "curavibe-runner"
primary_region = "bom"


[build]
builder = "paketobuildpacks/builder:base"


[env]
NODE_ENV = "production"


[http_service]
internal_port = 9_000
force_https = true
auto_stop_machines = false
auto_start_machines = true
